
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      -  DATABASE_URL=postgres://postgres:postgres@db:5432/inventory_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A inventory_management worker --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - .:/app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A inventory_management beat --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data: