# Generated by Django 4.2.7 on 2025-06-16 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
