# Generated by Django 4.2.7 on 2025-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_rename_qunatity_purchaseorder_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
